siothrun@siothrun:/media/siothrun/Backup/Thesis$ cd my_code/
siothrun@siothrun:/media/siothrun/Backup/Thesis/my_code$ ./batch_run.sh ag cruthú fothacair eolais go randamach
mkdir: ní féidir comhadlann `../copies/bioportal_randsub_4000/' a chruthú: File exists
^C
siothrun@siothrun:/media/siothrun/Backup/Thesis/my_code$ ^C
siothrun@siothrun:/media/siothrun/Backup/Thesis/my_code$ ./batch_run.sh 
ag cruthú fothacair eolais go randamach
mkdir: ní féidir comhadlann `../copies/bioportal_randsub_4000/' a chruthú: File exists
mkdir: ní féidir comhadlann `../models/bioportal_randsub_4000/' a chruthú: File exists
Ag réamh-phróiseáil na sonraí
ag scriosadh seaneolas i pbg_split agus pbg_out
ag fáil innéacsanna na dtacar
ag scríobh an eolais
ag rith algartaim leabaithe
ag fíorú na samhlach
Traceback (most recent call last):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 126, in do_eval_and_report_stats
    model = make_model(config)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/model.py", line 881, in make_model
    raise RuntimeError(
RuntimeError: Batch size (300) must be a multiple of num_batch_negs (500)
torchbiggraph_eval error: stopping script
ag cruthú fothacair eolais go randamach
mkdir: ní féidir comhadlann `../copies/dbsnp_randsub_4000/' a chruthú: File exists
mkdir: ní féidir comhadlann `../models/dbsnp_randsub_4000/' a chruthú: File exists
Ag réamh-phróiseáil na sonraí
ag scriosadh seaneolas i pbg_split agus pbg_out
ag fáil innéacsanna na dtacar
ag scríobh an eolais
ag rith algartaim leabaithe
ag fíorú na samhlach
Traceback (most recent call last):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 126, in do_eval_and_report_stats
    model = make_model(config)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/model.py", line 881, in make_model
    raise RuntimeError(
RuntimeError: Batch size (300) must be a multiple of num_batch_negs (500)
torchbiggraph_eval error: stopping script
ag cruthú fothacair eolais go randamach
mkdir: ní féidir comhadlann `../copies/drugbank_randsub_4000/' a chruthú: File exists
Ag réamh-phróiseáil na sonraí
ag scriosadh seaneolas i pbg_split agus pbg_out
ag fáil innéacsanna na dtacar
ag scríobh an eolais
ag rith algartaim leabaithe
ag fíorú na samhlach
Traceback (most recent call last):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 126, in do_eval_and_report_stats
    model = make_model(config)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/model.py", line 881, in make_model
    raise RuntimeError(
RuntimeError: Batch size (300) must be a multiple of num_batch_negs (500)
torchbiggraph_eval error: stopping script
ag cruthú fothacair eolais go randamach
Ag réamh-phróiseáil na sonraí
ag scriosadh seaneolas i pbg_split agus pbg_out
ag fáil innéacsanna na dtacar
ag scríobh an eolais
ag rith algartaim leabaithe
ag fíorú na samhlach
Traceback (most recent call last):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 126, in do_eval_and_report_stats
    model = make_model(config)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/model.py", line 881, in make_model
    raise RuntimeError(
RuntimeError: Batch size (300) must be a multiple of num_batch_negs (500)
torchbiggraph_eval error: stopping script
ag cruthú fothacair eolais go randamach
Ag réamh-phróiseáil na sonraí
ag scriosadh seaneolas i pbg_split agus pbg_out
ag fáil innéacsanna na dtacar
ag scríobh an eolais
ag rith algartaim leabaithe
ag fíorú na samhlach
Traceback (most recent call last):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 126, in do_eval_and_report_stats
    model = make_model(config)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/model.py", line 881, in make_model
    raise RuntimeError(
RuntimeError: Batch size (300) must be a multiple of num_batch_negs (500)
torchbiggraph_eval error: stopping script
exit_1 1
exit_2 1
exit_3 1
exit_4 1
exit_5 1
eolas deiridh
START_TIME 1622332493
RUNNING_TIME 772
START_DATE Domh 30 Beal 2021 00:54:53 IST
END_DATE Domh 30 Beal 2021 01:07:45 IST
críochnathe tar éis 772 soicind
siothrun@siothrun:/media/siothrun/Backup/Thesis/my_code$ 